import { GoogleGenerativeAI } from '@google/generative-ai';
import { config } from '../config/env';

const genAI = new GoogleGenerativeAI(config.googleApiKey!);
const model = genAI.getGenerativeModel({ model: 'gemini-1.5-pro' });

const securityPrompt = `
You are a Security Auditor AI agent. Analyze the provided code diff for security vulnerabilities.

Focus on:
- SQL injection vulnerabilities
- Hardcoded secrets (API keys, passwords, tokens)
- Data sanitization issues
- Authentication and authorization flaws
- Input validation problems

Context: {context}

Code Diff:
{diff}

Provide your analysis in a structured format. For each issue found, suggest a fix using GitHub's suggestion format:
\`\`\`suggestion
fixed code here
\`\`\`

If no issues, state "No security issues found."
`;

const performancePrompt = `
You are a Performance Auditor AI agent. Analyze the provided code diff for performance issues.

Focus on:
- O(n^2) or higher complexity loops
- Memory leaks (unclosed resources, large data structures)
- Inefficient API calls (N+1 queries, unnecessary requests)
- Blocking operations in async code
- Resource-intensive operations

Context: {context}

Code Diff:
{diff}

Provide your analysis in a structured format. For each issue found, suggest a fix using GitHub's suggestion format:
\`\`\`suggestion
fixed code here
\`\`\`

If no issues, state "No performance issues found."
`;

const architectPrompt = `
You are an Architecture Guardian AI agent. Analyze the provided code diff for architectural and code quality issues.

Focus on:
- Violation of project-specific tribal knowledge and patterns (from context)
- DRY (Don't Repeat Yourself) principle violations
- Code maintainability and readability
- Proper separation of concerns
- Adherence to established design patterns

Context: {context}

Code Diff:
{diff}

Provide your analysis in a structured format. For each issue found, suggest a fix using GitHub's suggestion format:
\`\`\`suggestion
fixed code here
\`\`\`

If no issues, state "No architectural issues found."
`;

export class AIAgentService {
  static async reviewCode(diff: string, context: string): Promise<string> {
    try {
      // Run all agents in parallel
      const [securityResponse, performanceResponse, architectResponse] = await Promise.all([
        this.runAgent(securityPrompt, diff, context),
        this.runAgent(performancePrompt, diff, context),
        this.runAgent(architectPrompt, diff, context),
      ]);

      // Aggregate responses
      return this.moderateResponses(securityResponse, performanceResponse, architectResponse);
    } catch (error) {
      console.error('Error in AI review:', error);
      throw new Error('Failed to perform AI code review');
    }
  }

  private static async runAgent(prompt: string, diff: string, context: string): Promise<string> {
    const formattedPrompt = prompt
      .replace('{context}', context)
      .replace('{diff}', diff);

    const result = await model.generateContent(formattedPrompt);
    const response = await result.response;
    return response.text();
  }

  private static moderateResponses(
    security: string,
    performance: string,
    architect: string
  ): string {
    const report = `# AI Code Review Report

## Security Analysis
${security}

## Performance Analysis
${performance}

## Architecture Analysis
${architect}

---
*This report was generated by Sentinel-AG's multi-agent AI review system.*
`;

    return report;
  }
}