import { Octokit } from '@octokit/rest';
import { config } from '../config/env';

const octokit = new Octokit({
  auth: config.githubToken,
});

export class GitHubPublisher {
  /**
   * Publishes the aggregated Multi-Agent review to GitHub.
   * Includes visual indicators for Severity and Cognitive Load.
   */
  static async postReviewComment(
    owner: string, 
    repo: string, 
    pullNumber: number, 
    body: string,
    severity: string,
    cognitiveLoad: number
  ): Promise<void> {
    
    // Add a Sentinel-AG Header with visual badges
    const statusEmoji = severity === 'High' ? '🔴' : severity === 'Medium' ? '🟡' : '🟢';
    const brandedBody = `
## 🤖 Sentinel-AG Analysis Report
**Status:** ${statusEmoji} ${severity} Risk | **Cognitive Load:** ${cognitiveLoad}/10

${body}

---
*Generated by Sentinel-AG: Agentic Framework for Affective Computing in PR Reviews.*
    `.trim();

    try {
      await octokit.pulls.createReview({
        owner,
        repo,
        pull_number: pullNumber,
        body: brandedBody,
        event: 'COMMENT', // Change to 'REQUEST_CHANGES' if severity is High to be more "Agentic"
      });
      console.log(`✅ Successfully published review to PR #${pullNumber}`);
    } catch (error: any) {
      console.error('❌ GitHub Publisher Error:', error.response?.data || error.message);
      throw new Error('Unable to publish GitHub review comment');
    }
  }
}